# Kotlin 嵌套试捕块

> 原文：<https://www.javatpoint.com/kotlin-nested-try-block>

我们还可以在需要的时候使用嵌套的 try 块。嵌套的 try catch 块是这样一种块，其中一个 try catch 块被实现到另一个 try 块中。

嵌套 try catch 块的要求是在一个代码块产生异常时出现的，在该代码块中，另一个代码语句也产生另一个异常。

### 嵌套 try 块的语法

```

.. 
try  
{  
    // code block 
    try  
    {  
        // code block 
    }  
    catch(e: SomeException)  
    {  
    }  
}  
catch(e: SomeException)  
{  
}  
..

```

**Kotlin 嵌套试块示例**

```

fun main(args: Array<String>) {
    val nume = intArrayOf(4, 8, 16, 32, 64, 128, 256, 512)
    val deno = intArrayOf(2, 0, 4, 4, 0, 8)
    try {
        for (i in nume.indices) {
            try {
                println(nume[i].toString() + " / " + deno[i] + " is " + nume[i] / deno[i])
            } catch (exc: ArithmeticException) {
                println("Can't divided by Zero!")
            }

        }
    } catch (exc: ArrayIndexOutOfBoundsException) {
        println("Element not found.")
    }
}

```

**输出:**

```
4 / 2 is 2
Can't divided by Zero!
16 / 4 is 4
32 / 4 is 8
Can't divided by Zero!
128 / 8 is 16
Element not found.

```