# 柯特林终于挡住了

> 原文:[https://www.javatpoint.com/kotlin-finally-block](https://www.javatpoint.com/kotlin-finally-block)

Kotlin **最后**阻塞这样的块，无论异常是否被处理，该块总是被执行。所以它被用来执行重要的代码语句。

### 柯特林最终阻止了示例 1

让我们看一个异常处理的例子，其中异常不会发生。

```

fun main (args: Array<String>){
    try {
        val data = 10 / 5
        println(data)
    } catch (e: NullPointerException) {
        println(e)
    } finally {
        println("finally block always executes")
    }
    println("below codes...")
}

```

**输出:**

```
2
finally block always executes
below codes...

```

### 柯特林最终阻止了示例 2

让我们来看一个异常处理的例子，其中*异常发生但没有被处理。*

```

fun main (args: Array<String>){
    try {
        val data = 5 / 0
        println(data)
    } catch (e: NullPointerException) {
        println(e)
    } finally {
        println("finally block always executes")
    }
    println("below codes...")
}

```

**输出:**

```
finally block always executes
Exception in thread "main" java.lang.ArithmeticException: / by zero

```

### 柯特林最终阻止了示例 3

我们来看一个异常处理的例子，其中*异常发生并被处理。*

```

fun main (args: Array<String>){
    try {
        val data = 5 / 0
        println(data)
    } catch (e: ArithmeticException) {
        println(e)
    } finally {
        println("finally block always executes")
    }
    println("below codes...")
}

```

**输出:**

```
java.lang.ArithmeticException: / by zero
finally block always executes
below codes...

```

#### 注意:如果程序退出(通过调用 exitProcess(Int)或任何导致进程中止的错误)，将不会执行 finally 块。